# Ajusta 'working-directory' a '.' si tus proyectos Python están en la raíz del repo
name: ci-python-bdd
on:
  push: { branches: ["**"] }
  pull_request:
permissions:
  contents: read
jobs:
  behave:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python-behave-template
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install deps (Behave)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          mkdir -p reports
      - name: Run Behave
        run: behave -f progress2 -f json.pretty -o reports/behave.json || true
      - name: Upload Behave report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: behave-report
          path: python-behave-template/reports/**

  pytest_bdd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python-pytest-bdd-template
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install deps (pytest-bdd)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          mkdir -p reports
      - name: Run pytest-bdd
        run: pytest -q --junitxml=reports/pytest-bdd.xml || true
      - name: Upload pytest report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-bdd-report
          path: python-pytest-bdd-template/reports/**
